version: "2.4"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certificates:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - certificate-manager

  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - ./certificates:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy:rw
    environment:
      - DEFAULT_EMAIL=mail@yourdomain.tld
    networks:
      - certificate-manager

  www:
    image: nginx
    restart: always
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=subdomain.yourdomain.tld
      - LETSENCRYPT_HOST=subdomain.yourdomain.tld
    networks:
      - certificate-manager

networks:
  certificate-manager:

volumes:
  vhost:
  html:
